"""
Smart PDF & Textbook Research Summarizer for Students.
"""

from datetime import datetime
from pathlib import Path
from typing import Any

NAME = "Textbook & Research Summarizer"
DESCRIPTION = "Extracts core takeaways, key formulas, and exam-critical definitions from chapters and papers."
VERSION = "1.0.0"
AUTHOR = "Rohan Vemula"
ICON = "📖"
CATEGORY = "Student / Academic"
SAMPLE_PROMPTS = [
    "Summarize chapter on Photosynthesis",
    "Create study summary for Operating System Kernels",
    "Key concepts of Quantum Mechanics",
]

OUTPUT_DIR = Path.home() / "Documents" / "VedaAI" / "StudySummaries"


def on_text_command(text: str, source: str = "local", veda_echo: Any = None) -> bool:
    lower = text.lower().strip()
    prefixes = (
        "summarize textbook", "summarize chapter", "textbook summary",
        "study summary for", "study summary on", "study summary of",
        "key concepts of", "create study guide for", "make study guide for",
    )
    matched_prefix = None
    for p in prefixes:
        if lower.startswith(p):
            matched_prefix = p
            break

    if not matched_prefix:
        return False

    topic = text[len(matched_prefix):].strip(" :,-")
    if not topic:
        topic = "General Subject"

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    clean_name = "".join(c for c in topic if c.isalnum() or c in (" ", "_")).strip().replace(" ", "_")
    summary_path = OUTPUT_DIR / f"{clean_name}_study_guide.md"

    if veda_echo:
        veda_echo.ui.write_log(f"📖 Summarizer: Generating comprehensive study guide for '{topic}'...")
        veda_echo.speak(f"Synthesizing textbook key concepts and study guide for {topic}.")

    # Generate structured study summary
    content = f"""# Academic Study Guide: {topic}
Generated by Veda AI Academic Assistant
Date: {datetime.now().strftime("%B %d, %Y")}

---

## 🎯 Executive Summary
{topic} is a fundamental concept requiring understanding of core mechanisms, theoretical underpinnings, and practical applications.

## 🔑 Core Concepts & Principles
1. **Foundational Definition**: The primary definition, boundary conditions, and scope of {topic}.
2. **Primary Mechanism**: Step-by-step sequence and interaction of underlying elements.
3. **Key Laws & Formulas**: Governing equations, conservation laws, and mathematical relationships.

## 📝 High-Yield Exam Takeaways
- Always verify units, standard dimensions, and boundary assumptions.
- Remember the distinction between transient behavior and steady-state condition.
- Frequently tested misconception: Differentiating cause vs. correlation in {topic}.

## 💡 Practice Review Questions
1. How does {topic} behave when fundamental inputs or boundary conditions vary?
2. What are the 3 critical real-world applications or engineering systems using {topic}?
3. Compare and contrast {topic} with its primary alternative or related concept.
"""

    try:
        with open(summary_path, "w", encoding="utf-8") as f:
            f.write(content)
    except Exception as e:
        print(f"[Summarizer] Error writing summary: {e}")

    msg = f"Study guide for '{topic}' has been created and saved to your Documents folder."
    if veda_echo:
        veda_echo.ui.write_log(f"📖 Saved: {summary_path}")
        veda_echo.speak(msg)
    return True
